# General Config

# Dev profile - MySQL

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/stayeasy?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DevTools
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=300ms
logging.level.org.springframework.boot.devtools=WARN

# JWT
application.security.jwt.secret=${JWT_SECRET:change-this-dev-secret-key-must-be-long-enough}
application.security.jwt.expiration=${JWT_EXPIRATION:3600000}

# Session
app.session.timeout-minutes=${SESSION_TIMEOUT_MINUTES:15}

# Gemini
gemini.api.key=${GEMINI_API_KEY:dummy-dev-key}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=}
